// Pure renderers for the published capability reference. Everything here is a
// function of what a booted server reported over `tools/list`, `resources/list`
// and `resources/templates/list`, plus the push-event table in
// `docs/push-events.md` — no hand-maintained tool list, no literal counts.
//
// `scripts/gen-tool-reference.mjs` does the I/O (boot, fetch, format, write);
// this module stays pure so the same input always yields the same bytes.

import { redactProtocolTokens } from './protocol-guard.js';

const GENERATED_BANNER =
  '<!-- Generated by scripts/gen-tool-reference.mjs. Do not edit by hand — run `npm run docs:reference`. -->';

const PUSH_EVENTS_DOC_URL = 'https://github.com/HJewkes/voltras-mcp/blob/main/docs/push-events.md';

export interface JsonSchemaNode {
  readonly type?: string | string[];
  readonly description?: string;
  readonly enum?: readonly unknown[];
  readonly minimum?: number;
  readonly maximum?: number;
  readonly items?: JsonSchemaNode;
}

export interface ToolInputSchema {
  readonly properties?: Readonly<Record<string, JsonSchemaNode>>;
  readonly required?: readonly string[];
}

export interface ToolSpec {
  readonly name: string;
  readonly description?: string;
  readonly inputSchema?: ToolInputSchema;
}

export interface ResourceSpec {
  readonly uri: string;
  readonly title?: string;
  readonly description?: string;
  readonly mimeType?: string;
}

export interface ResourceTemplateSpec {
  readonly uriTemplate: string;
  readonly title?: string;
  readonly description?: string;
  readonly mimeType?: string;
}

export interface PushEventRow {
  readonly event: string;
  readonly firesWhen: string;
  readonly autoStops: string;
}

export interface ReferenceInput {
  readonly coreToolNames: readonly string[];
  readonly mockToolNames: readonly string[];
  readonly tools: readonly ToolSpec[];
  readonly resources: readonly ResourceSpec[];
  readonly resourceTemplates: readonly ResourceTemplateSpec[];
  readonly pushEvents: readonly PushEventRow[];
}

export interface SidebarItem {
  readonly text: string;
  readonly link: string;
}

export interface ReferenceOutput {
  /** Relative path under the site root -> page body (before prettier). */
  readonly pages: ReadonlyMap<string, string>;
  readonly sidebar: readonly SidebarItem[];
  /** Protocol tokens redacted per tool name; a tool with none is absent. */
  readonly redactions: Readonly<Record<string, number>>;
}

const DEPRECATED_TAG = '@deprecated';
const EXPERIMENTAL_TAG = '@experimental';

/**
 * Strip the `@deprecated` / `@experimental` markers so they render as badges
 * rather than as the opening words of the summary. Only the bare tag and an
 * immediately-following dash separator are removed — the clause after it (what
 * to use instead) is the most useful sentence a deprecated tool has.
 */
function splitTags(description: string): { tags: string[]; body: string } {
  const tags: string[] = [];
  let body = description;
  let strippedHead = false;
  for (const tag of [DEPRECATED_TAG, EXPERIMENTAL_TAG]) {
    if (!body.includes(tag)) continue;
    tags.push(tag.slice(1));
    strippedHead ||= body.startsWith(tag);
    body = body.split(`${tag} — `).join('').split(`${tag} `).join('').split(tag).join('');
  }
  // Removing a leading tag leaves the clause after it mid-sentence ("prefer x"),
  // so restore the capital the tag was standing in for.
  const trimmed = body.trim();
  const head = strippedHead ? trimmed.charAt(0).toUpperCase() : trimmed.charAt(0);
  return { tags, body: head + trimmed.slice(1) };
}

/** First sentence of `text`, splitting only on terminators followed by space. */
function firstSentence(text: string): string {
  const match = /^[\s\S]*?[.!?](?=\s|$)/.exec(text);
  return (match ? match[0] : text).trim();
}

function oneLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

/** A human-readable type for one JSON Schema property. */
function describeType(node: JsonSchemaNode): string {
  if (node.enum) return node.enum.map((value) => `\`${String(value)}\``).join(' | ');
  const base = Array.isArray(node.type) ? node.type.join(' | ') : (node.type ?? 'any');
  if (base === 'array' && node.items) return `\`${describeItemType(node.items)}[]\``;
  const bounds = formatBounds(node);
  return `\`${base}\`${bounds}`;
}

function describeItemType(items: JsonSchemaNode): string {
  return Array.isArray(items.type) ? items.type.join('|') : (items.type ?? 'any');
}

/** A bound at the safe-integer edge is zod's `.int()` artifact, not a real limit. */
function realBound(value: number | undefined): number | undefined {
  if (value === undefined || Math.abs(value) >= Number.MAX_SAFE_INTEGER) return undefined;
  return value;
}

function formatBounds(node: JsonSchemaNode): string {
  const min = realBound(node.minimum);
  const max = realBound(node.maximum);
  if (min !== undefined && max !== undefined) return ` (${min}–${max})`;
  if (min !== undefined) return ` (min ${min})`;
  if (max !== undefined) return ` (max ${max})`;
  return '';
}

interface RenderedTool {
  readonly markdown: string;
  readonly redactions: number;
}

function renderParameters(schema: ToolInputSchema | undefined): {
  lines: string[];
  redactions: number;
} {
  const properties = schema?.properties ?? {};
  const names = Object.keys(properties);
  if (names.length === 0) return { lines: ['**Parameters:** none.'], redactions: 0 };
  const required = new Set(schema?.required ?? []);
  const lines = ['**Parameters**', ''];
  let redactions = 0;
  for (const name of names) {
    const node = properties[name] as JsonSchemaNode;
    const parts = [`- \`${name}\` — ${describeType(node)}`];
    parts.push(required.has(name) ? ', **required**.' : ', optional.');
    if (node.description) {
      const redacted = redactProtocolTokens(oneLine(node.description));
      redactions += redacted.count;
      parts.push(` ${redacted.text}`);
    }
    lines.push(parts.join(''));
  }
  return { lines, redactions };
}

function renderBadges(tags: readonly string[], mockOnly: boolean): string {
  const badges = tags.map((tag) => `<Badge type="warning" text="${tag}" />`);
  if (mockOnly) badges.push('<Badge type="tip" text="mock adapter only" />');
  return badges.join(' ');
}

function renderTool(tool: ToolSpec, mockOnly: boolean): RenderedTool {
  const { tags, body } = splitTags(tool.description ?? '');
  const redacted = redactProtocolTokens(body);
  const summary = firstSentence(redacted.text);
  const rest = redacted.text.slice(summary.length).trim();
  const params = renderParameters(tool.inputSchema);
  const badges = renderBadges(tags, mockOnly);
  const blocks = [`## \`${tool.name}\``, ''];
  if (badges) blocks.push(badges, '');
  blocks.push(summary || '_No description._', '');
  if (rest) blocks.push(rest, '');
  blocks.push(...params.lines);
  return { markdown: blocks.join('\n'), redactions: redacted.count + params.redactions };
}

function namespaceOf(toolName: string): string {
  return toolName.split('.')[0] as string;
}

/** Namespaces in registry order, each with its tool names in registry order. */
function groupByNamespace(names: readonly string[]): Map<string, string[]> {
  const groups = new Map<string, string[]>();
  for (const name of names) {
    const namespace = namespaceOf(name);
    const existing = groups.get(namespace);
    if (existing) existing.push(name);
    else groups.set(namespace, [name]);
  }
  return groups;
}

function pluralTools(count: number): string {
  return count === 1 ? '1 tool' : `${count} tools`;
}

function renderNamespacePage(
  namespace: string,
  toolNames: readonly string[],
  byName: ReadonlyMap<string, ToolSpec>,
  mockNames: ReadonlySet<string>,
  redactions: Record<string, number>,
): string {
  const sections: string[] = [];
  for (const name of toolNames) {
    const spec = byName.get(name);
    if (!spec) throw new Error(`the booted server did not report tool ${name}`);
    const rendered = renderTool(spec, mockNames.has(name));
    sections.push(rendered.markdown);
    if (rendered.redactions > 0) redactions[name] = rendered.redactions;
  }
  const header = [
    GENERATED_BANNER,
    '',
    `# \`${namespace}.*\``,
    '',
    `${pluralTools(toolNames.length)} in the \`${namespace}\` namespace.`,
    '',
  ];
  return `${header.join('\n')}${sections.join('\n\n')}\n`;
}

function renderIndexPage(input: ReferenceInput, groups: ReadonlyMap<string, string[]>): string {
  const core = input.coreToolNames.length;
  const total = core + input.mockToolNames.length;
  const mockNamespaces = new Set(input.mockToolNames.map(namespaceOf));
  const rows = [...groups].map(([namespace, names]) => {
    const availability = mockNamespaces.has(namespace) ? 'mock adapter only' : 'always registered';
    return `| [\`${namespace}.*\`](./${namespace}) | ${names.length} | ${availability} |`;
  });
  return [
    GENERATED_BANNER,
    '',
    '# Capability reference',
    '',
    'Everything on this page is generated from a running server: the generator boots',
    'voltras-mcp against the mock adapter and reads `tools/list`, so a description here',
    'is the description a client actually sees.',
    '',
    `**${core} tools** are registered with the real adapter (\`VOLTRA_ADAPTER=node\`) and`,
    `**${total}** in mock mode — the \`mock.*\` namespace is registered only when`,
    '`VOLTRA_ADAPTER=mock` and is stripped from `tools/list` otherwise.',
    '',
    '| Namespace | Tools | Availability |',
    '| --- | --- | --- |',
    ...rows,
    '',
    'See also [resources](./resources) and [push events](./push-events).',
    '',
  ].join('\n');
}

function renderResource(
  uri: string,
  spec: { title?: string; description?: string; mimeType?: string },
): string {
  const description = redactProtocolTokens(oneLine(spec.description ?? '')).text;
  const blocks = [`### \`${uri}\``, ''];
  if (spec.title) blocks.push(`**${spec.title}**`, '');
  blocks.push(description || '_No description._', '');
  blocks.push(`Content type: \`${spec.mimeType ?? 'application/json'}\`.`);
  return blocks.join('\n');
}

/** True when `uri` is one a template already covers, e.g. the `primary` listing. */
function coveredByTemplate(uri: string, templates: readonly ResourceTemplateSpec[]): boolean {
  return templates.some((template) => {
    const pattern = template.uriTemplate.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return new RegExp(`^${pattern.replace(/\\\{[a-zA-Z]+\\\}/g, '[^/]+')}$`).test(uri);
  });
}

function renderResourcesPage(input: ReferenceInput): string {
  const aliases = input.resources.filter((r) => !coveredByTemplate(r.uri, input.resourceTemplates));
  return [
    GENERATED_BANNER,
    '',
    '# Resources',
    '',
    'Each resource is a polling snapshot, templated by slot. Read `primary` for',
    'single-device flows, `left` / `right` when two units are connected.',
    '',
    '## Slot-templated resources',
    '',
    ...input.resourceTemplates.map((t) => renderResource(t.uriTemplate, t)),
    '',
    '## Legacy unslotted aliases',
    '',
    'Each template carries an unslotted alias that reads the primary slot, kept so',
    'single-device clients written before slots keep working.',
    '',
    ...aliases.map((r) => renderResource(r.uri, r)),
    '',
  ].join('\n');
}

function renderPushEventsPage(rows: readonly PushEventRow[]): string {
  const linked = rows.map((row) => ({
    ...row,
    firesWhen: row.firesWhen.replace(/\]\(#/g, `](${PUSH_EVENTS_DOC_URL}#`),
  }));
  return [
    GENERATED_BANNER,
    '',
    '# Push events',
    '',
    'The server pushes structured events as `notifications/claude/channel`, so a',
    'coaching surface learns that a rep finished without asking. This table is',
    'generated from [docs/push-events.md]' + `(${PUSH_EVENTS_DOC_URL}), which carries the`,
    'payload shapes and the enabling flags.',
    '',
    'It covers the events a coaching flow is built around and is **not guaranteed',
    'exhaustive** — the authoritative list is the set of publish sites under',
    '`src/state/`.',
    '',
    '| Event | Fires when | Auto-stops the set? |',
    '| --- | --- | --- |',
    ...linked.map((row) => `| ${row.event} | ${row.firesWhen} | ${row.autoStops} |`),
    '',
  ].join('\n');
}

/** Render every generated page from one booted server's answers. */
export function buildReference(input: ReferenceInput): ReferenceOutput {
  const byName = new Map(input.tools.map((tool) => [tool.name, tool]));
  const mockNames = new Set(input.mockToolNames);
  const groups = groupByNamespace([...input.coreToolNames, ...input.mockToolNames]);
  const pages = new Map<string, string>();
  const redactions: Record<string, number> = {};
  const sidebar: SidebarItem[] = [];
  for (const [namespace, toolNames] of groups) {
    pages.set(
      `reference/${namespace}.md`,
      renderNamespacePage(namespace, toolNames, byName, mockNames, redactions),
    );
    sidebar.push({ text: `${namespace}.*`, link: `/reference/${namespace}` });
  }
  pages.set('reference/index.md', renderIndexPage(input, groups));
  pages.set('reference/resources.md', renderResourcesPage(input));
  pages.set('reference/push-events.md', renderPushEventsPage(input.pushEvents));
  sidebar.unshift({ text: 'Overview', link: '/reference/' });
  sidebar.push(
    { text: 'Resources', link: '/reference/resources' },
    { text: 'Push events', link: '/reference/push-events' },
  );
  return { pages, sidebar, redactions };
}
