// Pure renderer for the pt-session skill's tool inventory page.
//
// The coach skill ships in this repo so it cannot be older than the server
// (VW-503). The half of it that names every tool is therefore not written by
// hand: it is a function of `CORE_TOOL_NAMES`, `TOOL_ACCESS` and the notes in
// `skill-inventory-notes.ts`. `scripts/gen-tool-reference.mjs` does the I/O;
// this module stays pure so the same registry always yields the same bytes.

import type { ToolAccess } from '../tool-registry.js';
import type { SkillToolJob, SkillToolNote } from './skill-inventory-notes.js';

const GENERATED_BANNER =
  '<!-- Generated by scripts/gen-tool-reference.mjs. Do not edit by hand — run `npm run docs:reference`. -->';

export interface SkillInventoryInput {
  readonly coreToolNames: readonly string[];
  readonly mockToolNames: readonly string[];
  readonly access: Readonly<Record<string, ToolAccess>>;
  /** Iteration order is the row order within each section. */
  readonly notes: Readonly<Record<string, SkillToolNote>>;
  readonly jobs: readonly SkillToolJob[];
  readonly verifiedLine: string;
}

/**
 * `D` alone already says read-only, which is why a read diagnostic renders as
 * one letter and a write diagnostic needs both.
 */
function accessLetter(access: ToolAccess, note: SkillToolNote): string {
  if (!note.diagnostic) return access === 'write' ? 'W' : 'R';
  return access === 'write' ? 'W D' : 'D';
}

/** A cell's own pipe would end the column early. */
function cell(text: string): string {
  return text.split('|').join('\\|');
}

function renderRow(name: string, letter: string, note: SkillToolNote): string {
  return `| \`${name}\` | ${letter} | ${cell(note.when)} | ${cell(note.rule)} |`;
}

function renderSection(
  job: SkillToolJob,
  index: number,
  entries: readonly [string, SkillToolNote][],
  input: SkillInventoryInput,
): string[] {
  const rows = entries.filter(([, note]) => note.job === job.id);
  if (rows.length === 0) throw new Error(`no tool is filed under the "${job.id}" section`);
  const lines = ['', `## ${index + 1}. ${job.heading}`, ''];
  if (job.note) lines.push(job.note, '');
  lines.push('| Tool | | When | The rule that matters |', '|---|---|---|---|');
  for (const [name, note] of rows) {
    const access = input.access[name];
    if (access === undefined) throw new Error(`${name} has an inventory note but no access class`);
    lines.push(renderRow(name, accessLetter(access, note), note));
  }
  return lines;
}

/** Every core tool needs a note, every note needs a core tool and a section. */
function assertNotesCoverRegistry(input: SkillInventoryInput): void {
  const sections = new Set(input.jobs.map((job) => job.id));
  for (const [name, note] of Object.entries(input.notes)) {
    if (!sections.has(note.job)) throw new Error(`${name} is filed under no section: ${note.job}`);
  }
  const noted = new Set(Object.keys(input.notes));
  const missing = input.coreToolNames.filter((name) => !noted.has(name));
  const extra = [...noted].filter((name) => !input.coreToolNames.includes(name));
  if (missing.length === 0 && extra.length === 0) return;
  throw new Error(
    `skill inventory notes and the registry disagree — missing: ${missing.join(', ') || 'none'}; ` +
      `not registered: ${extra.join(', ') || 'none'}`,
  );
}

// Each paragraph is emitted as ONE line: prettier's `proseWrap` is `preserve`,
// so a line break here survives into the page as a ragged one.
function renderHeader(input: SkillInventoryInput): string[] {
  const namespaces = new Set(input.coreToolNames.map((name) => name.split('.')[0]));
  return [
    GENERATED_BANNER,
    '',
    '# Tool inventory',
    '',
    '**When to read this.** You need a tool and do not know its name; OR you are unsure whether ' +
      'a tool exists on this server; OR you want the one rule that matters most for a tool ' +
      'before you call it.',
    '',
    `Every tool the server registers with the real adapter: **${input.coreToolNames.length} ` +
      `tools in ${namespaces.size} namespaces**, generated from the registry of the server this ` +
      `skill ships beside. ${input.verifiedLine}. The generated reference on the docs site ` +
      'carries the full descriptions. If a name here is missing from the harness, the live ' +
      'server is older than this skill; see the preflight in `14-sittings.md`. `mock.*` ' +
      `(${input.mockToolNames.length} tools) exists only under the mock adapter and is not ` +
      'listed.',
    '',
    'Names use dots here (`plan.block.schedule`). The harness shows underscores ' +
      '(`plan_block_schedule`).',
    '',
    'Key: **W** writes to the store or the device. **R** reads only. **D** is a diagnostic; ' +
      'never relay its output as a recommendation.',
  ];
}

const FOOTER = [
  '',
  '## Resources and push events',
  '',
  'Three `voltra://` resources and the push events are listed in ' +
    '`08-channel-events-reference.md`. Push arrives only when Claude Code was launched with ' +
    '`--channels plugin:voltras-channel@voltras-local`. Any other launch degrades to polling ' +
    'with no error.',
  '',
];

/** The whole page, before prettier. */
export function renderSkillInventory(input: SkillInventoryInput): string {
  assertNotesCoverRegistry(input);
  const entries = Object.entries(input.notes);
  const lines = renderHeader(input);
  for (const [index, job] of input.jobs.entries()) {
    lines.push(...renderSection(job, index, entries, input));
  }
  lines.push(...FOOTER);
  return `${lines.join('\n')}\n`;
}
