/**
 * Phase 1 SPA entry (VMCP-01.45).
 *
 * The full 4-panel dashboard rendered from `@titan-design/react-ui` components
 * (React Native primitives on web via react-native-web), at visual + functional
 * parity with the legacy vanilla-HTML dashboard (`dashboard-html.ts`). Polls the
 * sidecar's `/api/snapshot` every 500 ms; a separate 1 s tick drives the rest
 * count-up and the staleness watchdog, independent of the poll loop.
 *
 * The completed-set accumulation (set-log + session-progress totals) is folded
 * client-side by `reduceSnapshot` — a set is logged when `sets.active`
 * transitions non-null → null across polls (see adapter.ts).
 *
 * NDA: consumes `/api/snapshot` JSON only — no protocol bytes, frames, or
 * command codes cross this boundary.
 *
 * Theming: titan components emit Tailwind class strings (e.g. `text-text-primary`)
 * with no inline colors. Those classes are generated by the Tailwind PostCSS
 * pipeline (see postcss.config.cjs / tailwind.config.cjs) scanning the titan
 * dist, and resolve to the CSS variables in `theme/global.css` — whose `:root`
 * is dark by default (no theme-mode class/provider needed). Without this
 * pipeline the class strings have no backing CSS and text renders colorless.
 *
 * Color source of truth: titan's semantic `--color-*` tokens are the ONLY color
 * source in this dashboard — see `colors.ts` for the policy and the one place
 * that maps a semantic state (connection tone) onto a titan status token.
 */
import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '@titan-design/react-ui/theme/global.css';
import './dashboard.css';

import {
  buildBattery,
  buildConnectionStatus,
  buildCurrentSet,
  buildHeroSets,
  buildSessionProgress,
  fmtDisconnectClock,
  initialAccumulatorState,
  reduceSnapshot,
  type AccumulatorState,
  type Snapshot,
} from './adapter';
import { CONNECTION_TONE_TOKEN } from './colors';
import { buildBodyMapData } from './bodymap';
import { ExerciseHeroPanel } from './panels/ExerciseHeroPanel';
import { RestTimerPanel } from './panels/RestTimerPanel';
import { SessionProgressPanel } from './panels/SessionProgressPanel';
import { BodyMapPanel } from './panels/BodyMapPanel';
import { StrengthTrendPanel, type ExerciseTrendPoint } from './panels/StrengthTrendPanel';
import { MesoStatusPanel, type ProgramStatusView } from './panels/MesoStatusPanel';
import type { NextWorkoutView } from './panels/ExerciseHeroPanel';
import type { PrescriptionView } from './view-model/mappers';

const POLL_INTERVAL_MS = 500;
const TICK_INTERVAL_MS = 1000;
/** Strength trend is historical, not live — poll it slowly, and on exercise change. */
const TREND_INTERVAL_MS = 15_000;
const STALE_THRESHOLD_MS = POLL_INTERVAL_MS * 2;

type Status = 'ok' | 'stale' | 'error';

interface Model {
  snapshot: Snapshot | null;
  accumulator: AccumulatorState;
  status: Status;
  lastUpdate: string;
  nowMs: number;
  trend: ExerciseTrendPoint[];
  nextWorkout: NextWorkoutView | null;
  prescription: PrescriptionView | null;
  program: ProgramStatusView | null;
}

function useDashboardModel(): Model {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [accumulator, setAccumulator] = useState<AccumulatorState>(initialAccumulatorState);
  const [status, setStatus] = useState<Status>('ok');
  const [lastUpdate, setLastUpdate] = useState<string>('—');
  const [nowMs, setNowMs] = useState<number>(() => Date.now());
  const [trend, setTrend] = useState<ExerciseTrendPoint[]>([]);
  const [nextWorkout, setNextWorkout] = useState<NextWorkoutView | null>(null);
  const [prescription, setPrescription] = useState<PrescriptionView | null>(null);
  const [program, setProgram] = useState<ProgramStatusView | null>(null);
  const lastSuccessRef = useRef<number>(0);

  useEffect(() => {
    let cancelled = false;

    const poll = async (): Promise<void> => {
      try {
        const res = await fetch('/api/snapshot', { cache: 'no-store' });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = (await res.json()) as Snapshot;
        if (cancelled) return;
        const now = Date.now();
        lastSuccessRef.current = now;
        setSnapshot(data);
        setAccumulator((prev) => reduceSnapshot(prev, data, now));
        setStatus('ok');
        setLastUpdate(formatClock(new Date(now)));
        // Advance the clock in the same tick that may set restStartMs, so the
        // rest count-up reads `now - restStartMs === 0` at the transition rather
        // than a stale (pre-transition) `nowMs` that would go briefly negative.
        setNowMs(now);
      } catch {
        if (!cancelled) setStatus('error');
      }
    };

    void poll();
    const pollId = setInterval(() => void poll(), POLL_INTERVAL_MS);

    const tickId = setInterval(() => {
      if (cancelled) return;
      const now = Date.now();
      setNowMs(now);
      if (lastSuccessRef.current > 0 && now - lastSuccessRef.current > STALE_THRESHOLD_MS) {
        setStatus((prev) => (prev === 'error' ? 'error' : 'stale'));
      }
    }, TICK_INTERVAL_MS);

    return () => {
      cancelled = true;
      clearInterval(pollId);
      clearInterval(tickId);
    };
  }, []);

  // Strength trend: historical, so on its own slow cadence and refetched when the
  // active exercise changes (server resolves the active exercise when no id given).
  const exerciseName = snapshot?.session?.exerciseName ?? null;
  useEffect(() => {
    let cancelled = false;
    const fetchSlow = async (): Promise<void> => {
      try {
        const [trendRes, nextRes, planRes, programRes] = await Promise.all([
          fetch('/api/exercise-trend', { cache: 'no-store' }),
          fetch('/api/next-workout', { cache: 'no-store' }),
          fetch('/api/session-plan', { cache: 'no-store' }),
          fetch('/api/program-status', { cache: 'no-store' }),
        ]);
        if (trendRes.ok) {
          const data = (await trendRes.json()) as { points?: ExerciseTrendPoint[] };
          if (!cancelled) setTrend(data.points ?? []);
        }
        if (nextRes.ok) {
          const data = (await nextRes.json()) as { workout?: NextWorkoutView | null };
          if (!cancelled) setNextWorkout(data.workout ?? null);
        }
        if (planRes.ok) {
          const data = (await planRes.json()) as { plan?: PrescriptionView | null };
          if (!cancelled) setPrescription(data.plan ?? null);
        }
        if (programRes.ok) {
          const data = (await programRes.json()) as { program?: ProgramStatusView | null };
          if (!cancelled) setProgram(data.program ?? null);
        }
      } catch {
        // best-effort; keep the last-known values on a transient failure
      }
    };
    void fetchSlow();
    const id = setInterval(() => void fetchSlow(), TREND_INTERVAL_MS);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [exerciseName]);

  return {
    snapshot,
    accumulator,
    status,
    lastUpdate,
    nowMs,
    trend,
    nextWorkout,
    prescription,
    program,
  };
}

function formatClock(d: Date): string {
  const p = (n: number): string => String(n).padStart(2, '0');
  return `${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;
}

function App(): React.JSX.Element {
  const {
    snapshot,
    accumulator,
    status,
    lastUpdate,
    nowMs,
    trend,
    nextWorkout,
    prescription,
    program,
  } = useDashboardModel();

  const empty: Snapshot = { session: null, devices: [], sets: { active: null } };
  const snap = snapshot ?? empty;

  const currentSet = buildCurrentSet(snap);
  const heroSets = buildHeroSets(snap, accumulator.setLog);
  const progress = buildSessionProgress(snap, accumulator.setLog);
  const bodyMapData = buildBodyMapData(snap.activeExercise, accumulator.setLog.length);
  const connection = buildConnectionStatus(snap, status);
  const battery = buildBattery(snap);
  // Null (no set has ended yet) → "—". Otherwise the client-tracked count-up,
  // clamped so a clock skew never renders a negative M:SS.
  const restElapsedMs =
    accumulator.restStartMs == null ? null : Math.max(0, nowMs - accumulator.restStartMs);

  const toneColor = CONNECTION_TONE_TOKEN[connection.tone];

  return (
    <div className="dashboard">
      <header className="app-header">
        <h1 className="app-title">Voltras MCP</h1>
        {/* Connection is derived from the device snapshot, not just the poll.
            aria-live announces state changes; the text label makes the state
            legible without relying on color alone. */}
        <span className="status-chip" role="status" aria-live="polite">
          <span className="status-dot" style={{ color: toneColor }} aria-hidden="true">
            ●
          </span>
          <span className="status-label" style={{ color: toneColor }}>
            {connection.label}
          </span>
        </span>
        {battery.present && (
          <span
            className={`battery-chip${battery.low ? ' battery-low' : ''}`}
            aria-label={`battery ${battery.label}${battery.low ? ', low' : ''}`}
          >
            <span className="battery-icon" aria-hidden="true">
              {battery.low ? '🪫' : '🔋'}
            </span>
            <span className="battery-value">{battery.label}</span>
          </span>
        )}
        <span className="last-update">{lastUpdate}</span>
      </header>

      {connection.showBanner && (
        <div className="disconnect-banner" role="alert">
          <span className="disconnect-banner-title">Device disconnected</span>
          <span className="disconnect-banner-detail">
            {connection.disconnectedAt
              ? `Lost connection at ${fmtDisconnectClock(connection.disconnectedAt)} — readings below are the last known values.`
              : 'No live connection to the device — readings below may be stale.'}
          </span>
        </div>
      )}

      {/* Layout cohesion (Phase 6, VMCP-01.50): the current exercise is the HERO —
          its live metrics, velocity strip, and sets nested in one card — with the
          BodyMap / Session / Rest panels as a supporting rail, rather than five
          co-equal grid tiles. Mirrors the mobile app's exercise-centric flow. */}
      <main className="app-layout">
        <ExerciseHeroPanel
          exercise={progress.exercise}
          hasSession={progress.active}
          mode={currentSet.mode}
          currentSet={currentSet}
          heroSets={heroSets}
          historyBestE1rm={trend.length > 0 ? Math.max(...trend.map((p) => p.e1rm)) : null}
          nextWorkout={nextWorkout}
          prescription={prescription}
        />
        <aside className="support-rail" aria-label="Session overview">
          <SessionProgressPanel view={progress} />
          <MesoStatusPanel program={program} />
          <StrengthTrendPanel points={trend} />
          <RestTimerPanel elapsedMs={restElapsedMs} />
          <BodyMapPanel data={bodyMapData} />
        </aside>
      </main>
    </div>
  );
}

const container = document.getElementById('root');
if (container) {
  createRoot(container).render(<App />);
}
