/**
 * Dashboard SPA entry.
 *
 * Renders `LivePagePanel` (the north-star live page) from `@titan-design/react-ui`
 * components (React Native primitives on web via react-native-web) — the sole
 * dashboard surface. Polls the sidecar's `/api/snapshot` every 2 s as a
 * reconciliation backstop; the `/api/stream` SSE overlay carries the ~20 Hz live
 * data and instant structural pushes. A separate 1 s tick drives the rest
 * count-up and the staleness watchdog, independent of the poll loop.
 *
 * The completed-set accumulation (set-log + session-progress totals) is folded
 * client-side by `reduceSnapshot` — a set is logged when `sets.active`
 * transitions non-null → null across polls (see adapter.ts).
 *
 * Confidentiality: consumes `/api/snapshot` JSON only — no protocol bytes, frames, or
 * command codes cross this boundary.
 *
 * Theming: titan components emit Tailwind class strings (e.g. `text-text-primary`)
 * with no inline colors. Those classes are generated by the Tailwind PostCSS
 * pipeline (see postcss.config.cjs / tailwind.config.cjs) scanning the titan
 * dist, and resolve to the CSS variables in `theme/global.css` — whose `:root`
 * is dark by default (no theme-mode class/provider needed). Without this
 * pipeline the class strings have no backing CSS and text renders colorless.
 */
import React, { useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { useStore } from 'zustand';
// Brand faces (VW-68). titan components request `Space Grotesk` (headings), `Nunito Sans` (UI),
// and `Inter` (body) — by family name, via `--font-family-*` and inline styles — but nothing
// registered those @font-faces, so every one fell back to the system grotesque (a heavy,
// clashing heading). Self-host them (latin subset, the weights the design uses) so the wall
// renders the real type ramp offline, no CDN. Imported before the theme so the faces are
// declared when the first class resolves.
import '@fontsource/space-grotesk/latin-400.css';
import '@fontsource/space-grotesk/latin-500.css';
import '@fontsource/space-grotesk/latin-700.css';
import '@fontsource/nunito-sans/latin-400.css';
import '@fontsource/nunito-sans/latin-600.css';
import '@fontsource/nunito-sans/latin-700.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
import '@titan-design/react-ui/theme/global.css';

import { type Snapshot } from './adapter';
import { dashboardStore, type HistoricalPatch } from './store';
import { createLiveStreamController } from './live-stream';
import { LivePagePanel } from './panels/LivePagePanel';
import { readVariantOverride } from './live-page/stage-variant';
import { parseRoute, type Route } from './routing';
import { DashboardChrome } from './panels/DashboardChrome';
import { PlanBuilderPage } from './planner/PlanBuilderPage';
import { SessionSummaryPage } from './planner/SessionSummaryPage';
import type { PrescriptionView } from './adapter';

// Reconciliation backstop (VMCP-03.04): structural changes now arrive instantly via
// the `snapshot` SSE push, so the poll no longer needs to be fast. It stays as the
// correctness net that catches anything the stream misses (SSE unavailable/reconnecting,
// or a connection/settings change that isn't a set boundary).
const POLL_INTERVAL_MS = 2000;
const TICK_INTERVAL_MS = 1000;
/** Strength trend is historical, not live — poll it slowly, and on exercise change. */
const TREND_INTERVAL_MS = 15_000;

/**
 * Owns the store's I/O: the 2 s `/api/snapshot` poll + 1 s staleness tick, the
 * ~15 s prescription refetch (refetched when the active exercise changes), and the
 * live SSE subscription. Each just calls a store action — no component state lives
 * here. `LivePagePanel` reads the resulting store slices directly.
 */
function useDashboardController(): void {
  // Server resolves the active exercise when no id is given; refetch history on change.
  const exerciseName = useStore(dashboardStore, (s) => s.snapshot?.session?.exerciseName ?? null);

  useEffect(() => {
    let cancelled = false;
    const poll = async (): Promise<void> => {
      try {
        const res = await fetch('/api/snapshot', { cache: 'no-store' });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = (await res.json()) as Snapshot;
        if (cancelled) return;
        dashboardStore.getState().applySnapshot(data, Date.now());
      } catch {
        if (!cancelled) dashboardStore.getState().markError();
      }
    };

    void poll();
    const pollId = setInterval(() => void poll(), POLL_INTERVAL_MS);
    const tickId = setInterval(() => {
      if (!cancelled) dashboardStore.getState().tick(Date.now());
    }, TICK_INTERVAL_MS);

    return () => {
      cancelled = true;
      clearInterval(pollId);
      clearInterval(tickId);
    };
  }, []);

  useEffect(() => {
    let cancelled = false;
    const fetchSlow = async (): Promise<void> => {
      try {
        const planRes = await fetch('/api/session-plan', { cache: 'no-store' });
        if (cancelled) return;
        const patch: HistoricalPatch = {};
        if (planRes.ok)
          patch.prescription =
            ((await planRes.json()) as { plan?: PrescriptionView | null }).plan ?? null;
        dashboardStore.getState().applyHistorical(patch);
      } catch {
        // best-effort; keep the last-known values on a transient failure
      }
    };
    void fetchSlow();
    const id = setInterval(() => void fetchSlow(), TREND_INTERVAL_MS);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [exerciseName]);

  // The live SSE subscription now lives in the store; start it once. The overlay
  // frames feed `setLive`; the structural `snapshot` push feeds `applySnapshot`
  // (rev-guarded), so set/session boundaries reflect immediately without the poll.
  useEffect(
    () =>
      createLiveStreamController(
        (m, slot) => dashboardStore.getState().setLive(m, slot),
        (snap) => dashboardStore.getState().applySnapshot(snap, Date.now()),
      ),
    [],
  );
}

/** Subscribe to hash changes. The route is the single source of which page shows. */
function useHashRoute(): Route {
  const [route, setRoute] = React.useState(() => parseRoute(window.location.hash));
  useEffect(() => {
    const onChange = (): void => setRoute(parseRoute(window.location.hash));
    window.addEventListener('hashchange', onChange);
    return () => window.removeEventListener('hashchange', onChange);
  }, []);
  return route;
}

/** The page a route renders inside the shared chrome. */
function RoutePage(props: { route: Route }): React.JSX.Element | null {
  switch (props.route.name) {
    case 'plan':
      return <PlanBuilderPage />;
    case 'summary':
      return <SessionSummaryPage sessionId={props.route.sessionId} />;
    case 'live':
      return null;
  }
}

function App(): React.JSX.Element {
  useDashboardController();
  // The `?variant=` pin lets a tester force single/dual; WHICH stage shows is
  // otherwise a live decision `LivePagePanel` makes from the snapshot on every
  // frame (VMCP-04.07). Read once — it cannot change without a reload.
  const [variantOverride] = React.useState(() => readVariantOverride(window.location.search));
  const route = useHashRoute();
  // The live page owns its own chrome (it needs the non-scrolling wall layout and
  // renders a ColdBootView inside the shell); the planner routes share the same
  // `DashboardChrome` with scrolling turned on.
  if (route.name === 'live') return <LivePagePanel variantOverride={variantOverride} />;
  return (
    <DashboardChrome route={route} scroll>
      <RoutePage route={route} />
    </DashboardChrome>
  );
}

const container = document.getElementById('root');
if (container) {
  createRoot(container).render(<App />);
}
