// Rendering for the adaptive-rest simulation (VW-516): one JSON result and one
// markdown table. No personal values appear here; every number is synthetic.

import { ADAPTIVE_REST_POLICY, type RestIntentKey } from '../../src/analytics/adaptive-rest.js';
import type { FitScore, Stage1Verdict } from './stage1-baselines.js';
import type { Stage2Result } from './stage2-staircase.js';

/** One ship gate from design s.10.3. */
export interface Gate {
  readonly name: string;
  readonly passed: boolean;
  readonly detail: string;
}

export interface SimulationReport {
  readonly generatedFor: string;
  readonly policyVersion: string;
  readonly stage1: { fit: FitScore; verdict: Stage1Verdict };
  readonly stage2: readonly Stage2Result[];
  readonly gates: readonly Gate[];
  readonly defaultsMoved: readonly string[];
  readonly recommendations: readonly string[];
}

function round(value: number, places = 2): number {
  return Number(value.toFixed(places));
}

function pct(value: number): string {
  return `${round(value * 100, 1)}%`;
}

function tick(passed: boolean): string {
  return passed ? 'pass' : 'FAIL';
}

function stage1Table(verdict: Stage1Verdict): string {
  const rows = verdict.checks.map((entry) => {
    const expected = entry.tolerance === 0 ? `${round(entry.expected, 3)}` : `${entry.expected}`;
    const tolerance = entry.tolerance === 0 ? 'one-sided' : `±${pct(entry.tolerance)}`;
    return `| ${entry.name} | ${round(entry.observed, 3)} | ${expected} | ${tolerance} | ${tick(entry.passed)} |`;
  });
  return [
    '| Check | Simulated | Published | Tolerance | Verdict |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function fitTable(fit: FitScore): string {
  const rows = Object.entries(fit.params).map(
    ([key, value]) => `| \`${key}\` | ${round(value as number, 3)} |`,
  );
  return ['| Parameter | Fitted |', '| --- | --- |', ...rows].join('\n');
}

function stage2Table(results: readonly Stage2Result[], intent: RestIntentKey): string {
  const rows = results
    .filter((result) => result.intent === intent)
    .map(
      (result) =>
        `| ${result.lifter} | ${result.behaviour} | ${result.trueRestSec} | ${result.finalSec} | ` +
        `${result.daysToLearned ?? 'never'} | ${result.errorAtLearnedSec ?? 'n/a'} | ` +
        `${result.errorAtDay12Sec ?? 'n/a'} | ${pct(result.bounceAfterLearned)} | ` +
        `${pct(result.underRecoveredShare)} | ${pct(result.underRecoveredShareOnDefault)} | ` +
        `${round(result.restMinutesPerSession, 1)} | ${round(result.restMinutesPerSessionOnDefault, 1)} |`,
    );
  return [
    '| Population | Behaviour | True rest (s) | Final T (s) | Days to learned | Err at learned (s) | Err at day 12 (s) | Bounce after learned | Under-recovered | Same on default | Rest min/session | Same on default |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

/** Median of a sample, or null when it is empty. */
function median(values: readonly number[]): number | null {
  if (values.length === 0) return null;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 1 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

/**
 * The one number that explains most of the stage 2 table: how far the learned
 * value still is from the lifter's rest at the moment the record calls itself
 * learned, against how far it is nine days later.
 */
function convergenceSummary(results: readonly Stage2Result[]): string {
  const learned = results.filter((result) => result.daysToLearned !== null);
  const days = median(learned.map((result) => result.daysToLearned as number));
  const atLearned = median(learned.map((result) => Math.abs(result.errorAtLearnedSec ?? 0)));
  const atDay12 = median(
    results.filter((r) => r.errorAtDay12Sec !== null).map((r) => Math.abs(r.errorAtDay12Sec ?? 0)),
  );
  return [
    `Records that reached \`learned\`: ${learned.length} of ${results.length}.`,
    `Median exercise-days to \`learned\`: **${days ?? 'n/a'}**.`,
    `Median distance from the lifter's true rest at that moment: **${atLearned ?? 'n/a'} s**.`,
    `Median distance after 12 exercise-days: **${atDay12 ?? 'n/a'} s**.`,
  ].join(' ');
}

function gatesTable(gates: readonly Gate[]): string {
  const rows = gates.map((gate) => `| ${gate.name} | ${tick(gate.passed)} | ${gate.detail} |`);
  return ['| Ship gate | Verdict | Detail |', '| --- | --- | --- |', ...rows].join('\n');
}

const HEADER = `# VW-516: the adaptive-rest simulation

Generated by \`npm run sim:rest\` (\`scripts/sim/adaptive-rest-sim.ts\`). Every number below is
SYNTHETIC: it comes from a fitted model of a lifter, never from a recorded session. The
simulation imports the production rules from \`src/analytics/adaptive-rest.ts\` and
re-implements none of them, so a default changed in the module is the default these numbers
describe.

Seeded throughout. Re-running the command reproduces this file exactly.
`;

const STAGE1_INTRO = `## Stage 1: does the model reproduce published results?

Stage 2 means nothing until this passes. One model is fitted JOINTLY to all three baselines,
with the fatigue parameters shared and only the time constant varying by population, so
baseline B's two groups are a test of the model rather than a restatement of its parameters.

Published values are quoted from \`2026-09-19-vw-445-adaptive-rest-research.md\` s.2.2 and
s.2.4. No paper was re-read. Three figures are this simulation's ASSUMPTIONS, not the
papers': the number of sets in baseline A, and the rep target and reps-to-failure in
baseline C.
`;

const STAGE2_INTRO = `## Stage 2: the staircase on simulated lifters

Each row is one lifter, one behaviour and one intent over 14 exercise-days. "True rest" is
the rest at which that lifter's expected recovery ratio just reaches the target, measured on
a noiseless copy of the same lifter by bisection: it is the number the staircase is hunting.
Errors are signed, in seconds, against the true rest clamped into the floor and ceiling.

"Under-recovered" means a pair whose recovery ratio fell more than the measurement CV (4.5
points) BELOW the target, not merely under it. A staircase that converges on the target
leaves about half its pairs a hair under it by construction, so counting those would hand the
comparison to any rest long enough to be wasteful.
`;

function stage1Section(stage1: SimulationReport['stage1']): string {
  return [
    STAGE1_INTRO,
    `**Stage 1 verdict: ${stage1.verdict.passed ? 'PASSED' : 'FAILED'}.**`,
    '',
    stage1Table(stage1.verdict),
    '',
    '### The fit',
    '',
    fitTable(stage1.fit),
    '',
    `Self-selected rests, set by set (baseline C): ${stage1.verdict.baselineCRests.join(', ')} s.`,
  ].join('\n');
}

const PROVISIONAL = `> **Stage 1 did not pass, so everything below it is PROVISIONAL.** The design's rule is that
> the model must reproduce the published baselines before its verdicts on the staircase mean
> anything, and this run does not clear every one of them. The stage 2 tables describe what
> the staircase does to THIS model of a lifter; they are not yet evidence about a real one.
> No engineering default may be moved on this result, and none was.
`;

export function renderMarkdown(report: SimulationReport): string {
  return [
    HEADER,
    report.stage1.verdict.passed ? '' : PROVISIONAL,
    stage1Section(report.stage1),
    '',
    STAGE2_INTRO,
    '### Opening velocity (intent `strength`)',
    '',
    stage2Table(report.stage2, 'strength'),
    '',
    '### Reps preserved (no stated intent)',
    '',
    stage2Table(report.stage2, 'none'),
    '',
    '### What the two tables say in one line',
    '',
    convergenceSummary(report.stage2),
    '',
    '## Ship gates (design s.10.3)',
    '',
    gatesTable(report.gates),
    '',
    '## Recommendations',
    '',
    'Recommendations only. Nothing here was applied.',
    '',
    report.recommendations.map((line) => `- ${line}`).join('\n'),
    '',
    '## Defaults',
    '',
    report.defaultsMoved.length === 0
      ? 'No engineering default was moved by this run. Every number in `ADAPTIVE_REST_POLICY` is as the design set it.'
      : report.defaultsMoved.map((line) => `- ${line}`).join('\n'),
    '',
    `Policy version: \`${report.policyVersion}\`. The two recovery targets and the 15 s step are` +
      ' dose: the simulation may recommend moving them and may not move them.',
    '',
  ].join('\n');
}

export function policyVersion(): string {
  return ADAPTIVE_REST_POLICY.policyVersion;
}
