// Free-weight and machine lifts the imported training history names (VW-558, H1).
//
// The cable seed catalog cannot hold them: a barbell squat is not a cable squat, and
// pooling their loads under one id would corrupt every strength series. Each lift here
// has its own slug, is `cableEquivalent: false`, and never appears in `exercise.search`
// or the plan-builder list (`ExerciseService` hides it), so a live session cannot pick
// one. `getById` still resolves it, which is what history reads and the retro map need.

import type { Exercise, MuscleGroupId } from '@voltras/workout-analytics';

type Equipment = 'barbell' | 'dumbbell' | 'machine';
type Pattern = 'push' | 'pull' | 'squat' | 'hinge' | 'isolation';

interface Lift {
  id: string;
  name: string;
  aliases: string[];
  equipment: Equipment;
  pattern: Pattern;
  compound: boolean;
  muscleGroups: MuscleGroupId[];
  secondaryMuscleGroups?: MuscleGroupId[];
}

const EQUIPMENT_NAME: Record<Equipment, string> = {
  barbell: 'Barbell',
  dumbbell: 'Dumbbell',
  machine: 'Machine',
};

function toExercise(lift: Lift): Exercise {
  return {
    id: lift.id,
    name: lift.name,
    aliases: lift.aliases,
    muscleGroups: lift.muscleGroups,
    ...(lift.secondaryMuscleGroups === undefined
      ? {}
      : { secondaryMuscleGroups: lift.secondaryMuscleGroups }),
    movementPattern: lift.pattern,
    exerciseType: lift.compound ? 'compound' : 'isolation',
    equipment: [{ name: EQUIPMENT_NAME[lift.equipment], category: lift.equipment }],
    cableEquivalent: false,
    qualityScore: 50,
  };
}

const LIFTS: Lift[] = [
  // Barbell, push
  {
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    aliases: ['Press', 'Overhead Press', 'Seated Barbell Press'],
    equipment: 'barbell',
    pattern: 'push',
    compound: true,
    muscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['triceps'],
  },
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    aliases: ['Bench Press'],
    equipment: 'barbell',
    pattern: 'push',
    compound: true,
    muscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders', 'triceps'],
  },
  {
    id: 'barbell-close-grip-bench-press',
    name: 'Barbell Close Grip Bench Press',
    aliases: ['Close Grip Bench Press'],
    equipment: 'barbell',
    pattern: 'push',
    compound: true,
    muscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders', 'triceps'],
  },
  {
    id: 'barbell-pin-bench-press',
    name: 'Barbell Pin Bench Press',
    aliases: ['Pin Bench Press'],
    equipment: 'barbell',
    pattern: 'push',
    compound: true,
    muscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders', 'triceps'],
  },
  // Barbell, pull
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    aliases: ['Bent-Over Row'],
    equipment: 'barbell',
    pattern: 'pull',
    compound: true,
    muscleGroups: ['back'],
    secondaryMuscleGroups: ['biceps', 'shoulders'],
  },
  // Barbell, legs
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    aliases: ['Squat'],
    equipment: 'barbell',
    pattern: 'squat',
    compound: true,
    muscleGroups: ['quads'],
    secondaryMuscleGroups: ['glutes'],
  },
  {
    id: 'barbell-box-squat',
    name: 'Barbell Box Squat',
    aliases: ['Box Squat'],
    equipment: 'barbell',
    pattern: 'squat',
    compound: true,
    muscleGroups: ['quads'],
    secondaryMuscleGroups: ['glutes'],
  },
  {
    id: 'barbell-front-squat',
    name: 'Barbell Front Squat',
    aliases: ['Front Squat'],
    equipment: 'barbell',
    pattern: 'squat',
    compound: true,
    muscleGroups: ['quads'],
    secondaryMuscleGroups: ['glutes'],
  },
  {
    id: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    aliases: ['Deadlift'],
    equipment: 'barbell',
    pattern: 'hinge',
    compound: true,
    muscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['glutes', 'back', 'quads'],
  },
  {
    id: 'barbell-stiff-legged-deadlift',
    name: 'Barbell Stiff-Legged Deadlift',
    aliases: ['Stiff-Legged Deadlift'],
    equipment: 'barbell',
    pattern: 'hinge',
    compound: true,
    muscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['glutes'],
  },
  {
    id: 'barbell-romanian-deadlift',
    name: 'Barbell Romanian Deadlift',
    aliases: ['Romanian Deadlift', 'RDL Warmup'],
    equipment: 'barbell',
    pattern: 'hinge',
    compound: true,
    muscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['glutes'],
  },
  {
    id: 'barbell-sumo-deadlift',
    name: 'Barbell Sumo Deadlift',
    aliases: ['Sumo Deadlift'],
    equipment: 'barbell',
    pattern: 'hinge',
    compound: true,
    muscleGroups: ['glutes'],
    secondaryMuscleGroups: ['hamstrings', 'adductors', 'quads', 'back'],
  },
  {
    id: 'barbell-trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    aliases: ['Hex Bar Deadlift'],
    equipment: 'barbell',
    pattern: 'hinge',
    compound: true,
    muscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['quads', 'glutes', 'back'],
  },
  {
    id: 'barbell-rack-pull',
    name: 'Barbell Rack Pull',
    aliases: ['Rack Pull'],
    equipment: 'barbell',
    pattern: 'hinge',
    compound: true,
    muscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['glutes', 'back', 'traps'],
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    aliases: ['Hip Thrust'],
    equipment: 'barbell',
    pattern: 'hinge',
    compound: true,
    muscleGroups: ['glutes'],
  },
  // Barbell, arms
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    aliases: ['Drag Curl'],
    equipment: 'barbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['biceps'],
    secondaryMuscleGroups: ['forearms'],
  },
  {
    id: 'barbell-overhead-triceps-extension',
    name: 'Barbell Overhead Triceps Extension',
    aliases: ['Barbell French Press'],
    equipment: 'barbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['triceps'],
  },
  {
    id: 'barbell-lying-triceps-extension',
    name: 'Barbell Lying Triceps Extension',
    aliases: ['Lying Triceps Extension', 'Skull Crusher'],
    equipment: 'barbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['triceps'],
  },
  // Dumbbell
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    aliases: [],
    equipment: 'dumbbell',
    pattern: 'push',
    compound: true,
    muscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['triceps'],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    aliases: ['Seated Dumbbell Curl', 'Supinating Dumbbell Curl', 'Bent-Over Dumbbell Curl'],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['biceps'],
    secondaryMuscleGroups: ['forearms'],
  },
  {
    id: 'dumbbell-incline-curl',
    name: 'Incline Dumbbell Curl',
    aliases: [],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['biceps'],
    secondaryMuscleGroups: ['forearms'],
  },
  {
    id: 'dumbbell-incline-fly',
    name: 'Incline Dumbbell Fly',
    aliases: [],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders'],
  },
  {
    id: 'dumbbell-one-arm-row',
    name: 'One-Arm Dumbbell Row',
    aliases: ['One-Arm Row'],
    equipment: 'dumbbell',
    pattern: 'pull',
    compound: true,
    muscleGroups: ['back'],
    secondaryMuscleGroups: ['biceps', 'shoulders'],
  },
  {
    id: 'dumbbell-lying-triceps-extension',
    name: 'Lying Dumbbell Triceps Extension',
    aliases: [],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['triceps'],
  },
  {
    id: 'dumbbell-overhead-triceps-extension',
    name: 'Dumbbell Overhead Triceps Extension',
    aliases: [
      'French Press (Overhead Triceps Extension)',
      'Overhead Triceps Extension',
      'One-Arm Dumbbell Overhead Triceps Extension',
    ],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['triceps'],
  },
  {
    id: 'dumbbell-triceps-kickback',
    name: 'Dumbbell Triceps Kickback',
    aliases: ['Tricep Kickback', 'Kickback (unspecified)'],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['triceps'],
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    aliases: ['Lateral Raise'],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['shoulders'],
  },
  {
    id: 'machine-rear-delt-fly',
    name: 'Machine Rear Delt Fly',
    aliases: ['Rear Delt Fly'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['back'],
  },
  {
    id: 'dumbbell-bent-over-upright-row',
    name: 'Bent-Over Upright Row',
    aliases: [],
    equipment: 'dumbbell',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['traps'],
  },
  // Machine
  {
    id: 'machine-overhead-press',
    name: 'Machine Overhead Press',
    aliases: [],
    equipment: 'machine',
    pattern: 'push',
    compound: true,
    muscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['triceps'],
  },
  {
    id: 'machine-smith-incline-bench-press',
    name: 'Smith Machine Incline Bench Press',
    aliases: [],
    equipment: 'machine',
    pattern: 'push',
    compound: true,
    muscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders', 'triceps'],
  },
  {
    id: 'machine-chest-fly',
    name: 'Machine Chest Fly',
    aliases: ['Machine Chest Fly', 'Pec Deck'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders'],
  },
  {
    id: 'machine-lat-pulldown',
    name: 'Machine Lat Pulldown',
    aliases: ['Lat Pulldown'],
    equipment: 'machine',
    pattern: 'pull',
    compound: true,
    muscleGroups: ['back'],
    secondaryMuscleGroups: ['biceps'],
  },
  {
    id: 'machine-v-grip-lat-pulldown',
    name: 'Machine V-Grip Lat Pulldown',
    aliases: ['V-Grip Lat Pulldown'],
    equipment: 'machine',
    pattern: 'pull',
    compound: true,
    muscleGroups: ['back'],
    secondaryMuscleGroups: ['biceps'],
  },
  {
    id: 'machine-flexion-row',
    name: 'Machine Flexion Row',
    aliases: ['Flexion Row'],
    equipment: 'machine',
    pattern: 'pull',
    compound: true,
    muscleGroups: ['back'],
    secondaryMuscleGroups: ['biceps', 'shoulders'],
  },
  {
    id: 'machine-leg-press',
    name: 'Machine Leg Press',
    aliases: ['Leg Press', 'Leg Press (SS)'],
    equipment: 'machine',
    pattern: 'squat',
    compound: true,
    muscleGroups: ['quads'],
    secondaryMuscleGroups: ['glutes'],
  },
  {
    id: 'machine-pendulum-squat',
    name: 'Machine Pendulum Squat',
    aliases: ['Pendulum Squat'],
    equipment: 'machine',
    pattern: 'squat',
    compound: true,
    muscleGroups: ['quads'],
    secondaryMuscleGroups: ['glutes'],
  },
  {
    id: 'machine-knee-extension',
    name: 'Machine Knee Extension',
    aliases: ['Knee Extension', 'Leg Extension'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['quads'],
  },
  {
    id: 'machine-lying-leg-curl',
    name: 'Machine Lying Leg Curl',
    aliases: ['Lying Leg Curl'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['hamstrings'],
  },
  {
    id: 'machine-standing-calf-raise',
    name: 'Machine Standing Calf Raise',
    aliases: ['Standing Calf Raise'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['calves'],
  },
  {
    id: 'machine-seated-calf-raise',
    name: 'Machine Seated Calf Raise',
    aliases: ['Seated Calf Raise'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['calves'],
  },
  {
    id: 'machine-donkey-calf-raise',
    name: 'Machine Donkey Calf Raise',
    aliases: ['Donkey Calf Raise'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['calves'],
  },
  {
    id: 'machine-leg-press-calf-raise',
    name: 'Machine Leg Press Calf Raise',
    aliases: ['Leg Press Calf Raise'],
    equipment: 'machine',
    pattern: 'isolation',
    compound: false,
    muscleGroups: ['calves'],
  },
];

/** History lifts, loaded beside the cable seed at boot. */
export const HISTORY_SEED_EXERCISES: Exercise[] = LIFTS.map(toExercise);
