// Input schemas for the `baselines.*` tools (I5 / B56, VW-116).
//
// The key mirrors `@voltras/workout-analytics`'s public `BaselineKey`
// (`userId`, `exerciseId`, `setupId`, `side`) minus `userId`, which is the
// implicit local user.
//
// `setupId` names an inferred physical configuration (VW-119). The ids are
// GENERATED by the ROM clustering, so the only way to hold a valid one is to
// have seen it come back from `baselines.recalc { inferSetups: true }`; an
// invented id is rejected at the store boundary rather than silently answered
// with the pooled row. Omitted means the pooled, setup-agnostic baseline.
//
// `side` omitted means the side-agnostic view — a distinct baseline from
// either per-side one, not a wildcard over them.

import { z } from 'zod';

const BaselineKeyFields = {
  exerciseId: z.string().min(1),
  setupId: z.string().min(1).optional(),
  side: z.enum(['left', 'right']).optional(),
};

export const BaselinesGetInput = z.object(BaselineKeyFields).strict();

export const BaselinesRecalcInput = z
  .object({
    ...BaselineKeyFields,
    /**
     * Re-run the failure-anchor harvest filter over the key's stored sets
     * before deriving. Off by default: set close already harvests the set it
     * just wrote, so this is for history recorded before that hook shipped, or
     * for a filter-version bump that makes old verdicts re-scorable.
     */
    reharvest: z.boolean().optional(),
    /**
     * Re-run the ROM clustering over the exercise's working sets before
     * deriving, stamping `setup_id` onto each one (VW-119). Off by default and
     * run ONLY on request or at set close — there is no background loop.
     *
     * Idempotent: a re-run reproduces the same setup ids, so the cost of
     * setting it is a pass over sets already recorded, not a re-partition.
     */
    inferSetups: z.boolean().optional(),
  })
  .strict();
